-- Insert community student data from Sam's spreadsheet
-- Run this in Supabase SQL Editor
-- Updates existing deals with community fields, inserts new ones where no deal exists

-- First, update existing deals that match by client_name (case-insensitive)
-- Then insert any students that don't already exist as deals

DO $$
DECLARE
  rec RECORD;
BEGIN
  -- Create a temp table with all student data
  CREATE TEMP TABLE community_import (
    client_name text,
    sessions_total int,       -- 10 or null (Pro Group)
    session_count int,
    no_show_count int,
    community_notes text,
    mentor_name text
  );

  INSERT INTO community_import VALUES
    ('Ursalan Butt', 10, 8, 0, NULL, 'Henry Steeds'),
    ('Tony Phillips', 10, 2, 0, NULL, 'Henry Steeds'),
    ('Mik Bernicchi', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Andreas Georgiou', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Hanna Pawlos', NULL, 2, 0, NULL, 'Henry Steeds'),
    ('Gabriela Vonhaz', NULL, 5, 0, NULL, 'Henry Steeds'),
    ('Gerald Daly', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Maria Habib', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Meda Okaisu', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Robert Gastman', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Edward Busko', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Chris Thacker', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Wayne Harvey', 10, 4, 1, NULL, 'Henry Steeds'),
    ('Allen Scott', 10, 1, 0, NULL, 'Henry Steeds'),
    ('James Sheldrake', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Martyn Smith', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Deneth Mallawa', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Dave Hughes', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Anna Gray', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Veronica Maldonado', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('James Payton', 10, 2, 1, 'In challenge', 'Henry Steeds'),
    ('John Waddell', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Rory Smith', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Jimmy Theobalds', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Cheryl Fox', 10, 2, 0, NULL, 'Henry Steeds'),
    ('Tim Gaddes', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Mihaly Papp', 10, 2, 0, 'FUNDED', 'Henry Steeds'),
    ('George Barber', NULL, 5, 0, 'In challenge', 'Henry Steeds'),
    ('Charlotte Phillips', NULL, 4, 0, NULL, 'Henry Steeds'),
    ('Ian Jones', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Edward Watts', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Arunas Baranauskas', 10, 6, 0, 'In challenge', 'Henry Steeds'),
    ('Constantin Micu', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Jason Heaps', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Sam Wyss', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Jack Nix', 10, 2, 0, NULL, 'Henry Steeds'),
    ('Gerald Leech', NULL, 10, 1, 'In challenge', 'Henry Steeds'),
    ('David Flanagan', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Simon Royle', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Jens Edlund', NULL, 8, 0, 'In challenge', 'Henry Steeds'),
    ('Lise-Lotte Sikstrom', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Marcus Paybody', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Apostolos Arvanitidis', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Kyle Smith', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Hayward', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Alexander Axelsen', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Arjen Mertins', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Darren Stacey', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Lee Mcgalan', NULL, 1, 0, NULL, 'Henry Steeds'),
    ('Noel Stenson', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Colin Batney', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Steve Cooper', 10, 6, 0, 'FUNDED', 'Henry Steeds'),
    ('Louisa Baxter', NULL, 6, 0, NULL, 'Henry Steeds'),
    ('Nick Thompson', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Amrit Singh', 10, 2, 0, NULL, 'Henry Steeds'),
    ('James Marsh', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Timothy Bowhay', NULL, 14, 0, 'Challenge soon', 'Henry Steeds'),
    ('Stuart Brown', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Rita Horne', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Sophie Fletcher', NULL, 4, 2, NULL, 'Henry Steeds'),
    ('Nizamuddin Ismai', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Kyle Mckechnie', NULL, 10, 0, NULL, 'Henry Steeds'),
    ('Jessica Rodrigo', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Toby Skailes', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Jason Griffin', 10, 5, 0, NULL, 'Henry Steeds'),
    ('James Christow', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Jon Mcadam', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Jamie Scudamore', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Isabel Tang', NULL, 1, 0, NULL, 'Henry Steeds'),
    ('Martyn Tinge', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Adrian Lee', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Peter Johnson', NULL, 1, 1, NULL, 'Henry Steeds'),
    ('Richard De Silva', 10, 5, 0, 'Challenge soon', 'Henry Steeds'),
    ('Benny Johnson', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Chris Templeman', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Ross Brewer', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Saranjit Chahal', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Samsom Habte', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Craig Hoskin', 10, 0, 0, NULL, 'Henry Steeds'),
    ('James Munday', 10, 3, 0, NULL, 'Henry Steeds'),
    ('Robin Taylor', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Anton Zerle', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Graydon Robinson', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Hedley Woodman', NULL, 3, 0, NULL, 'Henry Steeds'),
    ('Mohammed Chowdhurry', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Oskar Winberg', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Stefan Stigendal', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Mark Sargent', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Joe Osbourne', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Nareej Raj', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Tom Burton', 10, 1, 0, NULL, 'Henry Steeds'),
    ('Sam Tobias', NULL, 8, 0, 'In challenge', 'Henry Steeds'),
    ('Andrew Benyon', NULL, 1, 0, NULL, 'Henry Steeds'),
    ('Lubna Hanif', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Tina Howe', NULL, 18, 0, 'Demo challenge', 'Henry Steeds'),
    ('Nick Hubbard', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('John Ward', NULL, 2, 0, NULL, 'Henry Steeds'),
    ('Anthony Cook', NULL, 8, 0, 'Demo challenge', 'Henry Steeds'),
    ('Jessie Garcia', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Steven Taylor-Smith', NULL, 3, 0, NULL, 'Henry Steeds'),
    ('Magnus Larson', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Baxter', NULL, 6, 0, NULL, 'Henry Steeds'),
    ('Paul Phillips', NULL, 4, 1, 'PASSED P1', 'Henry Steeds'),
    ('Josh Wilkinson', NULL, 2, 1, 'Demo challenge', 'Henry Steeds'),
    ('Abigail Miller', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Donna Quinlivin', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Gary Rhead', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Amandeep Sandu', NULL, 1, 0, NULL, 'Henry Steeds'),
    ('Daniel Alex Cook', NULL, 5, 3, 'FUNDED', 'Henry Steeds'),
    ('Karl Newby', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Neil Howe', NULL, 0, 1, NULL, 'Henry Steeds'),
    ('Maria Hassen', 10, 6, 3, NULL, 'Henry Steeds'),
    ('Rachel Jones', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Rafael Matarazatto', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Craig Potts', 10, 0, 1, NULL, 'Henry Steeds'),
    ('Brad Mckenzie', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('William Wood', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Gary Dalton', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Sean Mclaughlin', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Karen Moore', 10, 1, 0, 'In challenge', 'Henry Steeds'),
    ('Michael Bramwell', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Adrian Lockstone', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Mo Folorunsho', NULL, 2, 3, NULL, 'Henry Steeds'),
    ('Nick Blakemore', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Issac', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Ayman Yasir Ahmed', 10, 0, 0, NULL, 'Henry Steeds'),
    ('David Paines', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Christopher Stearman', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('James Edwards', 10, 0, 0, NULL, 'Henry Steeds'),
    ('William Jenkins', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Rizwan GulamHussein', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Glyn Hughes', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Owen Mceaney', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Nicky Sallas', 10, 2, 0, NULL, 'Henry Steeds'),
    ('Olivier Sage', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Bayly', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Alex Homan', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Jordi Van Den Berg', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Darren Layden', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Aras Puvan', 10, 0, 2, NULL, 'Henry Steeds'),
    ('Julie Miller', 10, 0, 0, NULL, 'Henry Steeds'),
    ('David Scott', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Suvanne Southgate', NULL, 1, 0, NULL, 'Henry Steeds'),
    ('Edward Pawsey', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Alec Lambrechts', 10, 2, 0, NULL, 'Henry Steeds'),
    ('Lorenzo Parmigiani', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Jones', 10, 0, 0, NULL, 'Henry Steeds'),
    ('James Parker', 10, 0, 0, NULL, 'Henry Steeds'),
    ('James Cann', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Dan Lynch', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Adam Kyriacou', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Harry Haynes', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Rodney Fortuin', 10, 0, 1, NULL, 'Henry Steeds'),
    ('David Elliot', 10, 0, 0, NULL, 'Henry Steeds'),
    ('William Kirkwood', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Alex Bartnick', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Neil Pandya', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Alex Burgh', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Daoud Assad', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Stuart Graham', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Freya Locke', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Andy Smith', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Evans', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Imran Iqbal', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Gemma Morgan', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Omid Atry', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Matt Oldroyd', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Layton Robinson', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Timothy Canning', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Paul Rudkowskyj', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('David Jarvis', 10, 0, 0, NULL, 'Henry Steeds'),
    ('Julian Boden', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Daniel Weaver', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Stuart Crane', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Kristeen Waugh', NULL, 0, 0, NULL, 'Henry Steeds'),
    ('Neil Southworth', NULL, 0, 0, NULL, 'Henry Steeds');

  -- Update existing deals with community data
  UPDATE deals d
  SET
    mentor_name = ci.mentor_name,
    session_count = ci.session_count,
    sessions_total = ci.sessions_total,
    no_show_count = ci.no_show_count,
    community_notes = ci.community_notes
  FROM community_import ci
  WHERE LOWER(TRIM(d.client_name)) = LOWER(TRIM(ci.client_name));

  -- Insert students that don't already exist as deals
  INSERT INTO deals (client_name, closer_id, closer_name, front_end, monthly_amount, programme, source, status,
                     mentor_name, session_count, sessions_total, no_show_count, community_notes)
  SELECT
    ci.client_name, 'lloyd', 'Lloyd', 0, 0, 'Kickstarter', 'manual', 'active',
    ci.mentor_name, ci.session_count, ci.sessions_total, ci.no_show_count, ci.community_notes
  FROM community_import ci
  WHERE NOT EXISTS (
    SELECT 1 FROM deals d WHERE LOWER(TRIM(d.client_name)) = LOWER(TRIM(ci.client_name))
  );

  DROP TABLE community_import;
END $$;
